// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI-zYuA_8mynLzuCdoXJdHSG4fCupftL0',
    appId: '1:801059030905:web:d398d9c603a957ac6651a8',
    messagingSenderId: '801059030905',
    projectId: 'edujarkom',
    authDomain: 'edujarkom.firebaseapp.com',
    storageBucket: 'edujarkom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JNkm9tWQ3wZ550x-Xj3zt1p0G-tunvQ',
    appId: '1:801059030905:android:712c68f7cb01384f6651a8',
    messagingSenderId: '801059030905',
    projectId: 'edujarkom',
    storageBucket: 'edujarkom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAECqmMprz9R5glQlHvWI9f2ZP41v6nmnc',
    appId: '1:801059030905:ios:e4bc74d36d3a226d6651a8',
    messagingSenderId: '801059030905',
    projectId: 'edujarkom',
    storageBucket: 'edujarkom.firebasestorage.app',
    iosBundleId: 'com.example.edujarkom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAECqmMprz9R5glQlHvWI9f2ZP41v6nmnc',
    appId: '1:801059030905:ios:e4bc74d36d3a226d6651a8',
    messagingSenderId: '801059030905',
    projectId: 'edujarkom',
    storageBucket: 'edujarkom.firebasestorage.app',
    iosBundleId: 'com.example.edujarkom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI-zYuA_8mynLzuCdoXJdHSG4fCupftL0',
    appId: '1:801059030905:web:142c9ca4ef321d7f6651a8',
    messagingSenderId: '801059030905',
    projectId: 'edujarkom',
    authDomain: 'edujarkom.firebaseapp.com',
    storageBucket: 'edujarkom.firebasestorage.app',
  );
}
